//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantDataMVC.DAL.EF.Entities_old
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeedBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeedBatch()
        {
            this.SeedTrays = new HashSet<SeedTray>();
        }
    
        public int Id { get; set; }
        public int SpeciesId { get; set; }
        public System.DateTime DateCollected { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        internal virtual Species Species { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<SeedTray> SeedTrays { get; set; }
        public virtual Site Site { get; set; }
    }
}
