//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantDataMVC.DAL.EF.Entities_old
{
    using System;
    using System.Collections.Generic;
    
    public partial class Species
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Species()
        {
            this.PlantStock = new HashSet<PlantStock>();
            this.SeedBatch = new HashSet<SeedBatch>();
        }
    
        public int Id { get; set; }
        public int GenusId { get; set; }
        public string LatinName { get; set; }
        public string CommonName { get; set; }
        public string Description { get; set; }
        public Nullable<int> PropagationTime { get; set; }
        public bool Native { get; set; }
    
        internal virtual Genus Genus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<PlantStock> PlantStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<SeedBatch> SeedBatch { get; set; }
    }
}
