// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace PlantDataMVC.Entities.Models
{

    // Genus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Genus
    {
        public override int Id { get; set; } // Id (Primary key)
        public string LatinName { get; set; } // LatinName (length: 30)

        // Reverse navigation

        /// <summary>
        /// Child Species where [Species].[GenusId] point to this entity (FK_Species_Genus)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Species> Species { get; set; } // Species.FK_Species_Genus

        public Genus()
        {
            Species = new System.Collections.Generic.List<Species>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
