// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace PlantDataMVC.Entities.Models
{

    // JournalEntryType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public partial class JournalEntryType
    {
        public override int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public int Effect { get; set; } // Effect

        // Reverse navigation

        /// <summary>
        /// Child JournalEntries where [JournalEntry].[JournalEntryTypeId] point to this entity (FK_Transactions_TransactionType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<JournalEntry> JournalEntries { get; set; } // JournalEntry.FK_Transactions_TransactionType

        public JournalEntryType()
        {
            JournalEntries = new System.Collections.Generic.List<JournalEntry>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
