// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace PlantDataMVC.Entities.Models
{

    // Plant
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Plant
    {
        [Required]
        [Display(Name = "Id")]
        public override int Id { get; set; } // Id (Primary key)

        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Latin name")]
        public string LatinName { get; set; } // LatinName (length: 30)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Specific name")]
        public string SpecificName { get; set; } // SpecificName (Primary key) (length: 30)

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Common name")]
        public string CommonName { get; set; } // CommonName (length: 50)

        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Description")]
        public string Description { get; set; } // Description (length: 200)

        [Display(Name = "Propagation time")]
        public int? PropagationTime { get; set; } // PropagationTime

        [Required]
        [Display(Name = "Native")]
        public bool Native { get; set; } // Native (Primary key)

        public Plant()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
