// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace PlantDataMVC.Entities.Models
{

    // SeedTray
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class SeedTray
    {
        [Required]
        [Display(Name = "Id")]
        public override int Id { get; set; } // Id (Primary key)

        [Required]
        [Display(Name = "Seed batch ID")]
        public int SeedBatchId { get; set; } // SeedBatchId

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Date planted")]
        public System.DateTime DatePlanted { get; set; } // DatePlanted

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Treatment")]
        public string Treatment { get; set; } // Treatment (length: 50)

        [Required]
        [Display(Name = "Thrown out")]
        public bool ThrownOut { get; set; } // ThrownOut

        // Reverse navigation

        /// <summary>
        /// Child JournalEntries where [JournalEntry].[SeedTrayId] point to this entity (FK_Transactions_SeedTray)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<JournalEntry> JournalEntries { get; set; } // JournalEntry.FK_Transactions_SeedTray

        // Foreign keys

        /// <summary>
        /// Parent SeedBatch pointed by [SeedTray].([SeedBatchId]) (FK_SeedTray_SeedBatch)
        /// </summary>
        public virtual SeedBatch SeedBatch { get; set; } // FK_SeedTray_SeedBatch

        public SeedTray()
        {
            JournalEntries = new System.Collections.Generic.List<JournalEntry>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
