//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PlantDataMVC.DAL.EF.Entities
{
    public partial class Genus
    {
        public Genus()
        {
            this.Species = new HashSet<Species>();
        }
    
        public int Id { get; set; }
        public string LatinName { get; set; }
    
        internal virtual ICollection<Species> Species { get; set; }
    }
    
}
