//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace PlantDataMVC.DAL.EF.Entities
{
    public partial class PlantDbContext : DbContext
    {
        public PlantDbContext()
            : base("name=PlantDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Genus> Genus { get; set; }
        public DbSet<JournalEntryType> JournalEntryTypes { get; set; }
        public DbSet<PlantStock> PlantStocks { get; set; }
        public DbSet<PriceListType> PriceListTypes { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<SeedBatch> SeedBatches { get; set; }
        public DbSet<SeedTray> SeedTrays { get; set; }
        public DbSet<Species> Species { get; set; }
        public DbSet<ProductPrice> ProductPrices { get; set; }
        public DbSet<JournalEntry> JournalEntries { get; set; }
        public DbSet<Site> Sites { get; set; }
    }
}
