//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PlantDataMVC.DAL.EF.Entities
{
    public partial class PlantStock
    {
        public PlantStock()
        {
            this.JournalEntries = new HashSet<JournalEntry>();
        }
    
        public int Id { get; set; }
        public int SpeciesId { get; set; }
        public int ProductTypeId { get; set; }
        public int QuantityInStock { get; set; }
    
        internal virtual ProductType ProductType { get; set; }
        internal virtual Species Species { get; set; }
        internal virtual ICollection<JournalEntry> JournalEntries { get; set; }
    }
    
}
