//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantDataMVC.DAL.EF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int PriceListTypeId { get; set; }
        public int ProductTypeId { get; set; }
        public decimal Price { get; set; }
        public System.DateTime DateEffective { get; set; }
    
        internal virtual PriceListType PriceListType { get; set; }
        internal virtual ProductType ProductType { get; set; }
    }
}
