<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ViewModels\Label\BarcodeLabelsPageViewModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework.Web\Framework.Web.csproj" />
    <ProjectReference Include="..\PlantData.Web.Mvc\PlantData.Web.Mvc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="EditModels\ProductPrice\" />
    <Folder Include="ViewModels\ProductPrice\" />
  </ItemGroup>

</Project>
