//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PlantDataMvc3.DAL.EF.Entities
{
    public partial class JournalEntryType
    {
        public JournalEntryType()
        {
            this.JournalEntries = new HashSet<JournalEntry>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Effect { get; set; }
    
        internal virtual ICollection<JournalEntry> JournalEntries { get; set; }
    }
    
}
