//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PlantDataMvc3.DAL.EF.Entities
{
    public partial class SeedBatch
    {
        public SeedBatch()
        {
            this.SeedTrays = new HashSet<SeedTray>();
        }
    
        public int Id { get; set; }
        public int SpeciesId { get; set; }
        public System.DateTime DateCollected { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        internal virtual Species Species { get; set; }
        internal virtual ICollection<SeedTray> SeedTrays { get; set; }
        public virtual Site Site { get; set; }
    }
    
}
