//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PlantDataMvc3.DAL.EF.Entities
{
    public partial class SeedTray
    {
        public SeedTray()
        {
            this.JournalEntries = new HashSet<JournalEntry>();
        }
    
        public int Id { get; set; }
        public int SeedBatchId { get; set; }
        public System.DateTime DatePlanted { get; set; }
        public string Treatment { get; set; }
        public bool ThrownOut { get; set; }
    
        internal virtual SeedBatch SeedBatch { get; set; }
        internal virtual ICollection<JournalEntry> JournalEntries { get; set; }
    }
    
}
