//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PlantDataMvc3.DAL.EF.Entities
{
    public partial class Site
    {
        public Site()
        {
            this.SeedBatches = new HashSet<SeedBatch>();
        }
    
        public int Id { get; set; }
        public string SiteName { get; set; }
        public string Suburb { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    
        public virtual ICollection<SeedBatch> SeedBatches { get; set; }
    }
    
}
