SET IDENTITY_INSERT [dbo].[Site] ON
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (1, N'(Dad)                         ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (2, N'(Dad) Dromana                 ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (3, N'Beerwah SA                    ', N'Beerwah', CAST(-26.86000 AS Decimal(8, 5)), CAST(152.99000 AS Decimal(8, 5)))
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (4, N'Beverly Hill St', N'Moorooka', CAST(-27.53000 AS Decimal(8, 5)), CAST(153.03000 AS Decimal(8, 5)))
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (5, N'Brisbane Koala Bushlands      ', NULL, CAST(11.00000 AS Decimal(8, 5)), CAST(11.00000 AS Decimal(8, 5)))
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (6, N'Bunya Mountains            ', NULL, CAST(1.12346 AS Decimal(8, 5)), CAST(1.12346 AS Decimal(8, 5)))
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (7, N'Chermside                     ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (8, N'Cnr Woodville & Marjorie Sts, ', N'Moorooka', CAST(0.00000 AS Decimal(8, 5)), CAST(0.00000 AS Decimal(8, 5)))
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (9, N'CSIRO, Pullenvale             ', N'Pullenvale', CAST(10.00000 AS Decimal(8, 5)), CAST(1.00000 AS Decimal(8, 5)))
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (10, N'Fairfield                     ', NULL, CAST(-25.00000 AS Decimal(8, 5)), CAST(153.00000 AS Decimal(8, 5)))
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (11, N'Gap Creek                     ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (12, N'Glendale Grove, Moorooka      ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (13, N'Griffith Uni, Nathan          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (14, N'Hawks Nest                    ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (15, N'Home                          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (16, N'Ipswich Rd Annerley           ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (17, N'Karawatha                     ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (18, N'Koala Park, Moorooka          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (19, N'Lake Manchester               ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (20, N'Maroochydore                  ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (21, N'Mt Gravatt                    ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (22, N'Mt Mellum                     ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (23, N'Northview Outlook, Moorooka   ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (24, N'Oxley Creek Common            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (25, N'Percy St Park Tarragindi      ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (26, N'Percy St Park, Tarragindi     ', N'Tarragindi', CAST(0.00000 AS Decimal(8, 5)), CAST(0.00000 AS Decimal(8, 5)))
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (27, N'Rafting Ground Reserve        ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (28, N'Rafting Ground Reserve, Pullen', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (29, N'Sarah St, Moorooka; Koala Park', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (30, N'SGAP Qld Region Meeting       ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (31, N'Sherwood Arboretum            ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (32, N'Sparkes Hill                  ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (33, N'Sydney Harbour Foreshore      ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (34, N'Tarragindi Rd Moorooka        ', N'Moorooka', CAST(0.00000 AS Decimal(8, 5)), CAST(0.00000 AS Decimal(8, 5)))
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (35, N'Tarragindi Rd, Annerley       ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (36, N'Tarragindi Reservoir          ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (37, N'Tennessee Ave, Moorooka       ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (38, N'Toohey Forest                 ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (39, N'Unknown                       ', NULL, CAST(0.00000 AS Decimal(8, 5)), CAST(0.00000 AS Decimal(8, 5)))
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (40, N'Unknown, Home                 ', NULL, CAST(0.00000 AS Decimal(8, 5)), CAST(0.00000 AS Decimal(8, 5)))
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (41, N'White Rock                    ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (42, N'Whites Hill                   ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (43, N'Woolloongabba                 ', NULL, NULL, NULL)
INSERT INTO [dbo].[Site] ([Id], [SiteName], [Suburb], [Latitude], [Longitude]) VALUES (44, N'My test site', NULL, CAST(153.12345 AS Decimal(8, 5)), CAST(-27.11111 AS Decimal(8, 5)))
SET IDENTITY_INSERT [dbo].[Site] OFF
