SET IDENTITY_INSERT [dbo].[SeedTray] ON
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (87, 6, N'2010-11-17', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (88, 7, N'2010-12-02', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (89, 10, N'2010-11-17', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (90, 11, N'2011-01-13', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (91, 12, N'2011-01-13', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (92, 13, N'2011-01-13', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (93, 16, N'2010-08-20', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (94, 17, N'2010-10-11', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (95, 18, N'2010-12-13', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (96, 20, N'2010-12-01', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (97, 22, N'2011-01-27', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (98, 24, N'2010-06-08', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (99, 25, N'2010-06-08', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (100, 26, N'2010-12-13', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (101, 29, N'2010-06-08', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (102, 33, N'2010-11-27', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (103, 34, N'2010-09-28', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (104, 35, N'2010-10-15', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (105, 36, N'2010-11-03', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (106, 39, N'2010-12-13', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (107, 40, N'2011-01-10', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (108, 41, N'2011-01-10', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (109, 42, N'2010-04-08', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (110, 43, N'2010-12-01', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (111, 44, N'2010-12-16', N'Tray, sterilised mix                              ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (112, 44, N'2010-12-16', N'On a brick                                        ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (113, 44, N'2010-12-16', N'Pots                                              ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (114, 45, N'2010-11-03', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (115, 46, N'2010-12-16', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (116, 47, N'2010-11-13', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (117, 50, N'2010-12-16', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (118, 51, N'2010-11-27', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (119, 52, N'2010-11-04', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (120, 53, N'2010-11-16', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (121, 54, N'2011-01-10', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (122, 59, N'2010-11-27', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (123, 60, N'2010-12-06', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (124, 61, N'2010-11-13', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (125, 62, N'2010-12-06', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (126, 63, N'2010-12-01', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (127, 65, N'2010-11-13', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (128, 67, N'2010-12-01', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (129, 69, N'2010-12-06', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (130, 71, N'2011-01-10', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (131, 72, N'2011-01-10', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (132, 73, N'2010-10-27', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (133, 76, N'2010-11-05', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (134, 77, N'2010-12-16', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (135, 78, N'2010-12-23', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (136, 79, N'2010-12-16', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (137, 80, N'2010-10-15', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (138, 84, N'2011-01-10', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (139, 86, N'2011-02-03', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (140, 91, N'2011-01-10', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (141, 92, N'2010-10-11', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (142, 93, N'2011-02-02', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (143, 94, N'2011-01-10', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (144, 98, N'2010-08-20', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (145, 100, N'2010-10-11', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (146, 101, N'2010-11-13', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (147, 103, N'2010-11-13', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (148, 104, N'2010-11-27', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (149, 105, N'2010-11-13', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (150, 106, N'2011-01-10', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (151, 108, N'2011-01-06', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (152, 109, N'2011-02-02', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (153, 112, N'2010-07-20', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (154, 113, N'2010-09-28', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (155, 114, N'2010-04-08', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (156, 118, N'2011-01-10', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (157, 120, N'2010-12-16', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (158, 121, N'2010-12-16', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (159, 122, N'2011-02-02', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (160, 126, N'2010-11-16', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (161, 127, N'2011-01-10', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (162, 128, N'2011-02-02', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (163, 129, N'2010-11-05', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (164, 131, N'2011-01-10', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (165, 132, N'2010-12-06', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (166, 133, N'2010-12-06', N'                                                  ', 1)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (167, 136, N'2011-02-02', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (168, 137, N'2011-02-02', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (169, 139, N'2010-11-16', N'                                                  ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (170, 21, N'2011-02-21', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (171, 50, N'2011-02-21', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (172, 48, N'2011-02-21', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (173, 73, N'2011-02-21', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (174, 74, N'2011-02-21', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (175, 75, N'2011-02-21', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (176, 96, N'2011-02-21', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (177, 100, N'2011-02-21', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (178, 107, N'2011-02-21', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (179, 117, N'2011-02-21', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (180, 144, N'2011-02-16', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (181, 160, N'2011-03-31', N'None                                              ', 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (182, 166, N'2011-03-31', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (183, 155, N'2011-03-31', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (184, 153, N'2011-03-31', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (185, 80, N'2011-03-31', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (186, 138, N'2011-03-31', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (187, 164, N'2011-03-31', NULL, 0)
INSERT INTO [dbo].[SeedTray] ([Id], [SeedBatchId], [DatePlanted], [Treatment], [ThrownOut]) VALUES (188, 142, N'2011-03-31', NULL, 0)
SET IDENTITY_INSERT [dbo].[SeedTray] OFF
