SET IDENTITY_INSERT [dbo].[SeedBatch] ON
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (4, 139, N'2010-12-27', N'Hawks Nest                    ', NULL, NULL)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (5, 140, N'2010-01-01', N'Oxley Creek Common            ', NULL, 24)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (6, 141, N'2010-01-01', N'Sarah St, Moorooka; Koala Park', NULL, 29)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (7, 142, N'2010-01-01', N'Koala Park, Moorooka          ', NULL, 18)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (8, 143, N'2010-01-01', N'Oxley Creek Common            ', NULL, 24)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (9, 144, N'2010-11-20', N'Sydney Harbour Foreshore      ', NULL, 33)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (10, 145, N'2010-10-30', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (11, 146, N'2010-12-27', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (12, 147, N'2010-12-27', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (13, 148, N'2010-12-27', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (14, 149, N'2010-12-01', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (15, 150, N'2011-02-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (16, 151, N'2010-08-18', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (17, 152, N'2010-10-05', N'Lake Manchester               ', NULL, 19)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (18, 153, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (19, 154, N'2010-12-14', N'Whites Hill                   ', NULL, 42)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (20, 155, N'2010-08-29', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (21, 156, N'2011-02-18', N'Beverly Hill St, Moorooka     ', NULL, 4)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (22, 157, N'2011-01-16', N'Beverly Hill St, Moorooka     ', NULL, 4)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (23, 158, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (24, 159, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (25, 160, N'2010-01-01', N'Northview Outlook, Moorooka   ', NULL, 23)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (26, 162, N'2010-01-01', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (27, 163, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (28, 164, N'2010-12-27', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (29, 165, N'2010-01-01', N'Beverly Hill St, Moorooka     ', NULL, 4)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (30, 166, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (31, 167, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (32, 168, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (33, 169, N'2010-01-01', N'Unknown                       ', NULL, 39)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (34, 172, N'2010-07-29', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (35, 173, N'2010-08-29', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (36, 174, N'2010-10-30', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (37, 175, N'2011-01-20', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (38, 176, N'2010-12-07', N'Fairfield                     ', NULL, 10)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (39, 177, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (40, 178, N'2010-12-27', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (41, 179, N'2010-12-14', N'Whites Hill                   ', NULL, 42)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (42, 180, N'2010-01-01', N'CSIRO, Pullenvale             ', NULL, 9)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (43, 181, N'2010-01-01', N'Glendale Grove, Moorooka      ', NULL, 12)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (44, 182, N'2010-12-14', N'Whites Hill                   ', NULL, 42)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (45, 183, N'2010-11-01', N'Chermside                     ', NULL, 7)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (46, 184, N'2010-12-13', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (47, 185, N'2010-11-12', N'Percy St Park, Tarragindi     ', NULL, 26)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (48, 186, N'2011-02-17', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (49, 187, N'2010-01-01', N'Oxley Creek Common            ', NULL, 24)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (50, 188, N'2010-12-14', N'Gap Creek                     ', NULL, 11)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (51, 189, N'2010-10-30', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (52, 190, N'2010-10-30', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (53, 191, N'2010-10-27', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (54, 192, N'2011-01-06', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (55, 193, N'2010-08-18', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (56, 194, N'2010-11-20', N'Sydney Harbour Foreshore      ', NULL, 33)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (57, 195, N'2011-02-07', N'Tarragindi Rd Moorooka        ', NULL, 34)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (58, 196, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (59, 197, N'2010-11-12', N'Percy St Park Tarragindi      ', NULL, 25)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (60, 198, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (61, 199, N'2010-11-05', N'Tarragindi Reservoir          ', NULL, 36)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (62, 200, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (63, 201, N'2010-11-30', N'Oxley Creek Common            ', NULL, 24)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (64, 202, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (65, 203, N'2010-11-05', N'Cnr Woodville & Marjorie Sts, ', NULL, 8)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (66, 203, N'2010-12-07', N'Fairfield                     ', NULL, 10)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (67, 204, N'2010-11-30', N'Oxley Creek Common            ', NULL, 24)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (68, 205, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (69, 206, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (70, 207, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (71, 208, N'2010-12-27', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (72, 209, N'2010-12-27', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (73, 210, N'2010-11-12', N'Ipswich Rd Annerley           ', NULL, 16)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (74, 211, N'2010-11-12', N'Percy St Park Tarragindi      ', NULL, 25)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (75, 212, N'2010-11-12', N'Percy St Park Tarragindi      ', NULL, 25)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (76, 213, N'2010-10-30', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (77, 214, N'2010-12-13', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (78, 215, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (79, 216, N'2010-12-13', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (80, 217, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (81, 218, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (82, 219, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (83, 221, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (84, 222, N'2010-10-26', N'Brisbane Koala Bushlands      ', NULL, 5)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (85, 223, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (86, 224, N'2011-01-09', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (87, 225, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (88, 226, N'2010-08-18', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (89, 227, N'2010-12-27', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (90, 228, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (91, 229, N'2010-10-30', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (92, 230, N'2010-10-01', N'Woolloongabba                 ', NULL, 43)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (93, 231, N'2010-10-30', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (94, 232, N'2010-12-27', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (95, 233, N'2010-08-18', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (96, 237, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (97, 234, N'2010-01-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (98, 235, N'2010-08-18', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (99, 236, N'2010-10-01', N'(Dad)                         ', NULL, 1)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (100, 238, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (101, 239, N'2010-11-05', N'Tarragindi Rd, Annerley       ', NULL, 35)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (102, 240, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (103, 241, N'2010-01-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (104, 242, N'2010-01-01', N'CSIRO, Pullenvale             ', NULL, 9)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (105, 243, N'2010-01-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (106, 244, N'2010-12-20', N'Sherwood Arboretum            ', NULL, 31)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (107, 245, N'2010-12-20', N'Sherwood Arboretum            ', NULL, 31)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (108, 246, N'2010-12-27', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (109, 247, N'2010-12-27', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (110, 248, N'2010-11-30', N'Oxley Creek Common            ', NULL, 24)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (111, 250, N'2010-01-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (112, 251, N'2010-10-01', N'(Dad) Dromana                 ', NULL, 2)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (113, 252, N'2010-10-01', N'Tennessee Ave, Moorooka       ', NULL, 37)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (114, 253, N'2010-11-30', N'Oxley Creek Common            ', NULL, 24)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (115, 254, N'2010-11-13', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (116, 256, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (117, 257, N'2010-12-20', N'Sherwood Arboretum            ', NULL, 31)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (118, 258, N'2010-12-20', N'Sherwood Arboretum            ', NULL, 31)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (119, 259, N'2010-08-18', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (120, 260, N'2010-12-14', N'Whites Hill                   ', NULL, 42)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (121, 261, N'2010-12-14', N'Whites Hill                   ', NULL, 42)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (122, 262, N'2011-01-20', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (123, 265, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (124, 263, N'2010-10-30', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (125, 264, N'2010-10-30', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (126, 267, N'2010-10-30', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (127, 268, N'2010-12-14', N'Whites Hill                   ', NULL, 42)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (128, 269, N'2010-12-14', N'Rafting Ground Reserve, Pullen', NULL, 28)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (129, 270, N'2010-10-30', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (130, 270, N'2010-12-20', N'Sherwood Arboretum            ', NULL, 31)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (131, 271, N'2010-12-27', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (132, 272, N'2010-12-06', N'Beverly Hill St, Moorooka     ', NULL, 4)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (133, 273, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (134, 274, N'2010-01-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (135, 275, N'2010-01-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (136, 276, N'2011-01-20', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (137, 278, N'2010-10-01', N'Home                          ', NULL, 15)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (138, 279, N'2010-08-18', N'Toohey Forest                 ', NULL, 38)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (139, 280, N'2010-01-01', N'Northview Outlook, Moorooka   ', NULL, 23)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (140, 208, N'2011-02-25', N'Mt Gravatt                    ', NULL, 21)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (141, 286, N'2011-02-26', N'Rafting Ground Reserve        ', NULL, 27)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (142, 283, N'2011-02-26', N'White Rock                    ', NULL, 41)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (143, 284, N'2011-02-26', N'Rafting Ground Reserve        ', NULL, 27)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (144, 290, N'2011-02-14', N'SGAP Qld Region Meeting       ', NULL, 30)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (145, 291, N'2011-03-04', N'Unknown                       ', NULL, 39)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (146, 292, N'2011-03-04', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (147, 192, N'2011-03-04', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (148, 290, N'2011-03-04', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (149, 293, N'2011-03-04', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (150, 294, N'2011-03-04', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (151, 295, N'2011-03-04', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (152, 296, N'2011-03-26', N'Bunya Mountains               ', NULL, 6)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (153, 297, N'2011-03-14', N'Unknown, Home                 ', N'From SGAP meeting and my garden                                                                                                                                                                         ', 40)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (154, 298, N'2011-03-19', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (155, 299, N'2011-03-19', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (156, 300, N'2011-03-19', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (157, 301, N'2011-03-19', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (158, 302, N'2011-03-17', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (159, 303, N'2011-03-19', N'Mt Mellum                     ', NULL, 22)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (160, 304, N'2011-03-26', N'Bunya Mountains               ', NULL, 6)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (161, 305, N'2011-03-16', N'Griffith Uni, Nathan          ', NULL, 13)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (162, 226, N'2011-03-16', N'Griffith Uni, Nathan          ', NULL, 13)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (163, 306, N'2011-03-16', N'Griffith Uni, Nathan          ', NULL, 13)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (164, 307, N'2011-03-16', N'Griffith Uni, Nathan          ', NULL, 13)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (166, 308, N'2011-03-16', N'Griffith Uni, Nathan          ', NULL, 13)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (167, 309, N'2011-03-16', N'Griffith Uni, Nathan          ', NULL, 13)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (168, 309, N'2011-03-16', N'Griffith Uni, Nathan          ', NULL, 13)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (169, 323, N'2011-04-15', N'Sparkes Hill                  ', NULL, 32)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (170, 324, N'2011-04-25', N'Beerburrum                    ', NULL, 3)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (171, 325, N'2011-04-25', N'Beerburrum                    ', NULL, 3)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (172, 326, N'2011-04-25', N'Beerburrum                    ', NULL, 3)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (173, 327, N'2011-04-25', N'Beerburrum                    ', NULL, 3)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (174, 328, N'2011-04-25', N'Beerburrum                    ', NULL, 3)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (175, 150, N'2011-04-23', N'Maroochydore                  ', NULL, 20)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (176, 329, N'2011-04-30', N'Griffith Uni, Nathan          ', NULL, 13)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (177, 330, N'2011-04-30', N'Griffith Uni, Nathan          ', NULL, 13)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (178, 331, N'2011-04-30', N'Griffith Uni, Nathan          ', NULL, 13)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (179, 283, N'2011-04-30', N'Griffith Uni, Nathan          ', NULL, 13)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (180, 322, N'2011-04-09', N'Karawatha                     ', NULL, 17)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (181, 139, N'2010-12-30', N'Hawks Nest                    ', NULL, 14)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (185, 142, N'2017-08-03', N'home', N'testing', NULL)
INSERT INTO [dbo].[SeedBatch] ([Id], [SpeciesId], [DateCollected], [Location], [Notes], [SiteId]) VALUES (186, 140, N'2017-08-02', NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[SeedBatch] OFF
