// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace PlantDataMVC.DAL.EF.Configuration
{
    using PlantDataMVC.DAL.EF.Context;
    using PlantDataMVC.DAL.EF.Entities;

    // Genus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public partial class GenusConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Genus>
    {
        public GenusConfiguration()
            : this("dbo")
        {
        }

        public GenusConfiguration(string schema)
        {
            ToTable("Genus", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.LatinName).HasColumnName(@"LatinName").HasColumnType("nvarchar").IsRequired().HasMaxLength(30);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
