// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace PlantDataMVC.DAL.EF.Configuration
{
    using PlantDataMVC.DAL.EF.Context;
    using PlantDataMVC.DAL.EF.Entities;

    // Site
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public partial class SiteConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Site>
    {
        public SiteConfiguration()
            : this("dbo")
        {
        }

        public SiteConfiguration(string schema)
        {
            ToTable("Site", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SiteName).HasColumnName(@"SiteName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Suburb).HasColumnName(@"Suburb").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Latitude).HasColumnName(@"Latitude").HasColumnType("decimal").IsOptional().HasPrecision(18,0);
            Property(x => x.Longitude).HasColumnName(@"Longitude").HasColumnType("decimal").IsOptional().HasPrecision(18,0);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
