<?xml version="1.0" encoding="utf-8"?><Database Name="PlantData" ContextNamespace="PlantDataMVC.DAL.LinqToSqlEntities" Class="PlantDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TIMOTHYMCMAS-PC;Initial Catalog=PlantData;Integrated Security=True;MultipleActiveResultSets=True" SettingsObjectName="PlantDataMVC.DAL.Properties.Settings" SettingsPropertyName="PlantDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.JournalEntry" Member="JournalEntries" AccessModifier="Internal">
    <Type Name="JournalEntry">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlantStockId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JournalEntryTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SeedTrayId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="JournalEntryType_JournalEntry" Member="JournalEntryType" AccessModifier="Internal" ThisKey="JournalEntryTypeId" OtherKey="Id" Type="JournalEntryType" IsForeignKey="true" />
      <Association Name="PlantStock_JournalEntry" Member="PlantStock" AccessModifier="Internal" ThisKey="PlantStockId" OtherKey="Id" Type="PlantStock" IsForeignKey="true" />
      <Association Name="SeedTray_JournalEntry" Member="SeedTray" AccessModifier="Internal" ThisKey="SeedTrayId" OtherKey="Id" Type="SeedTray" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JournalEntryType" Member="JournalEntryTypes" AccessModifier="Internal">
    <Type Name="JournalEntryType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Effect" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="JournalEntryType_JournalEntry" Member="JournalEntries" AccessModifier="Internal" ThisKey="Id" OtherKey="JournalEntryTypeId" Type="JournalEntry" />
    </Type>
  </Table>
  <Table Name="dbo.PlantStock" Member="PlantStocks" AccessModifier="Internal">
    <Type Name="PlantStock">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SpeciesId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuantityInStock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PlantStock_JournalEntry" Member="JournalEntries" AccessModifier="Internal" ThisKey="Id" OtherKey="PlantStockId" Type="JournalEntry" />
      <Association Name="ProductType_PlantStock" Member="ProductType" AccessModifier="Internal" ThisKey="ProductTypeId" OtherKey="Id" Type="ProductType" IsForeignKey="true" />
      <Association Name="Species_PlantStock" Member="Species" ThisKey="SpeciesId" OtherKey="Id" Type="Species" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PriceListType" Member="PriceListTypes" AccessModifier="Internal">
    <Type Name="PriceListType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Kind" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Association Name="PriceListType_ProductPrice" Member="ProductPrices" AccessModifier="Internal" ThisKey="Id" OtherKey="PriceListTypeId" Type="ProductPrice" />
    </Type>
  </Table>
  <Table Name="dbo.ProductPrice" Member="ProductPrices" AccessModifier="Internal">
    <Type Name="ProductPrice">
      <Column Name="PriceListTypeId" Storage="_PriceListId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateEffective" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="PriceListType_ProductPrice" Member="PriceListType" AccessModifier="Internal" ThisKey="PriceListTypeId" OtherKey="Id" Type="PriceListType" IsForeignKey="true" />
      <Association Name="ProductType_ProductPrice" Member="ProductType" AccessModifier="Internal" ThisKey="ProductTypeId" OtherKey="Id" Type="ProductType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductType" Member="ProductTypes" AccessModifier="Internal">
    <Type Name="ProductType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ProductType_PlantStock" Member="PlantStocks" AccessModifier="Internal" ThisKey="Id" OtherKey="ProductTypeId" Type="PlantStock" />
      <Association Name="ProductType_ProductPrice" Member="ProductPrices" AccessModifier="Internal" ThisKey="Id" OtherKey="ProductTypeId" Type="ProductPrice" />
    </Type>
  </Table>
  <Table Name="dbo.Genus" Member="Genus" AccessModifier="Internal">
    <Type Name="Genus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LatinName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Genus_Species" Member="Species" AccessModifier="Internal" ThisKey="Id" OtherKey="GenusId" Type="Species" />
    </Type>
  </Table>
  <Table Name="dbo.Species" Member="Species" AccessModifier="Internal">
    <Type Name="Species">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GenusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LatinName" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CommonName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="PropagationTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Native" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Species_PlantStock" Member="PlantStocks" ThisKey="Id" OtherKey="SpeciesId" Type="PlantStock" />
      <Association Name="Species_SeedBatch1" Member="SeedBatches" ThisKey="Id" OtherKey="SpeciesId" Type="SeedBatch" />
      <Association Name="Genus_Species" Member="Genus" AccessModifier="Internal" ThisKey="GenusId" OtherKey="Id" Type="Genus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SeedTray" Member="SeedTrays" AccessModifier="Internal">
    <Type Name="SeedTray">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SeedBatchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DatePlanted" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Treatment" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="ThrownOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="SeedTray_JournalEntry" Member="JournalEntries" AccessModifier="Internal" ThisKey="Id" OtherKey="SeedTrayId" Type="JournalEntry" />
      <Association Name="SeedBatch1_SeedTray" Member="SeedBatch" ThisKey="SeedBatchId" OtherKey="Id" Type="SeedBatch" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Site" Member="Sites">
    <Type Name="Site">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Suburb" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Site_SeedBatch1" Member="SeedBatches" ThisKey="Id" OtherKey="SiteId" Type="SeedBatch" />
    </Type>
  </Table>
  <Table Name="dbo.SeedBatch" Member="SeedBatches">
    <Type Name="SeedBatch">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SpeciesId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCollected" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SiteId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SeedBatch1_SeedTray" Member="SeedTrays" ThisKey="Id" OtherKey="SeedBatchId" Type="SeedTray" />
      <Association Name="Site_SeedBatch1" Member="Site" ThisKey="SiteId" OtherKey="Id" Type="Site" IsForeignKey="true" />
      <Association Name="Species_SeedBatch1" Member="Species" ThisKey="SpeciesId" OtherKey="Id" Type="Species" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetSpeciesByGenus" Method="GetSpeciesByGenus" AccessModifier="Internal" IsComposable="true">
    <Parameter Name="genusName" Type="System.String" DbType="NChar(30)" />
    <ElementType Name="GetSpeciesByGenusResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GenusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Species" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CommonName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="PropagationTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Native" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertSpecies" Method="InsertSpecies" AccessModifier="Internal">
    <Parameter Name="genusName" Type="System.String" DbType="NChar(30)" />
    <Parameter Name="speciesName" Type="System.String" DbType="NChar(30)" />
    <Parameter Name="commonName" Type="System.String" DbType="NChar(50)" />
    <Parameter Name="description" Type="System.String" DbType="NChar(200)" />
    <Parameter Name="maxPropagationTime" Type="System.Int32" DbType="Int" />
    <Parameter Name="isNative" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateSpecies" Method="UpdateSpecies" AccessModifier="Internal">
    <Parameter Name="speciesId" Type="System.Int32" DbType="Int" />
    <Parameter Name="genusName" Type="System.String" DbType="NChar(30)" />
    <Parameter Name="speciesName" Type="System.String" DbType="NChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertSeedBatchBySpeciesId" Method="InsertSeedBatchBySpeciesId" AccessModifier="Internal">
    <Parameter Name="speciesId" Type="System.Int32" DbType="Int" />
    <Parameter Name="dateCollected" Type="System.DateTime" DbType="Date" />
    <Parameter Name="location" Type="System.String" DbType="NChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertSeedTrayByBatchId" Method="InsertSeedTrayByBatchId" AccessModifier="Internal">
    <Parameter Name="batchId" Type="System.Int32" DbType="Int" />
    <Parameter Name="datePlanted" Type="System.DateTime" DbType="Date" />
    <Parameter Name="treatment" Type="System.String" DbType="NChar(50)" />
    <Parameter Name="disposed" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetPrice" Method="GetPrice" AccessModifier="Internal" IsComposable="true">
    <Parameter Name="pricelistId" Type="System.Int32" DbType="Int" />
    <Parameter Name="productTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="transactionDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Decimal" />
  </Function>
</Database>