

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "PlantDataMVC.Entities\App.config"
//     Connection String Name: "PlantDataDbContext"
//     Connection String:      "Data Source=(LocalDB)\v11.0;AttachDbFilename=G:\Storage\Coding\Visual Studio Projects\PlantDataMVCApp\PlantDataMVC.UI\App_Data\PlantDataDB.mdf;Integrated Security=True"
// ------------------------------------------------------------------------------------------------

// -----------------------------------------------------------------------------------------
// Failed to read database schema in LoadTables() - An attempt to attach an auto-named database for file G:\Storage\Coding\Visual Studio Projects\PlantDataMVCApp\PlantDataMVC.UI\App_Data\PlantDataDB.mdf failed. A database with the same name exists, or specified file cannot be opened, or it is located on UNC share.
// -----------------------------------------------------------------------------------------

