// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace PlantDataMVC.Entities.Context
{
    using PlantDataMVC.Entities.Configuration;
    using PlantDataMVC.Entities.Interfaces;
    using PlantDataMVC.Entities.Models;

    public partial class PlantDataDbContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<PlantDataDbContext>
    {
        public PlantDataDbContext Create()
        {
            return new PlantDataDbContext();
        }
    }
}
// </auto-generated>
